sudo: required
language: generic
services:
- docker
script:
- wget -O- https://raw.githubusercontent.com/harisvsulaiman/element-build/master/script.sh
  | sh -
branches: null
except:
- /^debian\/\d/
after_success:
- openssl aes-256-cbc -K $encrypted_224e37c23f87_key -iv $encrypted_224e37c23f87_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
